# IMPORT PACKAGE PANDAS

In [14]:
import pandas as pd

In [15]:
df = pd.read_csv("playstation_4_games.csv")

# MEMBACA FILE CSV

In [16]:
df

,ID,GamePSID,GameName,Publisher,ReleaseYear,ReleaseDate,Developer,Genre,Features,Size,Medium,Hardware,CompletionTime(Hours),is_Digital_game,is_Physical_game,OfficialWebsite
0,1,3045,Q*Bert Rebooted,LOOT Interactive,2015.0,2015-02-17,Gonzo Games,Action,"PS Plus, PS Now",109.00,NaN,NaN,NaN,0,0,http://www.sidelineamusements.com/qbert/
1,2,3051,Q*Bert Rebooted (EU),LOOT Interactive,2015.0,2015-07-22,LOOT Interactive,Action,PS Now,127.00,Digital only,NaN,NaN,0,0,http://www.sidelineamusements.com/qbert/
2,3,6703,Q.U.B.E. 2,Trapped Nerve Games,2018.0,2018-03-13,Toxic Games,"Puzzle, Platformer",NaN,2682.88,Digital only,NaN,NaN,0,0,http://qube-game.com/
3,4,3403,Q.U.B.E. Director's Cut,GRIP Digital,2015.0,2015-07-21,Toxic Games,"Puzzle, Platformer",PS Plus,1945.60,Digital only,NaN,3-4,0,0,http://qube-game.com/
4,5,13176,Quake (PS4),Bethesda Softworks,2021.0,2021-08-19,"MachineGames, Nightdive Studios, id Software",First Person Shooter,NaN,NaN,Physical and Digital,NaN,NaN,0,0,https://bethesda.net/en/game/quake
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9681,9682,10928,9th Dawn III,Valorware,2020.0,2020-10-06,Valorware,"Open World, Action-RPG, Role Playing",NaN,653.00,Physical and Digital,NaN,NaN,0,0,https://valorware.squarespace.com/9th-dawn-iii
9682,9683,10929,9th Dawn III (EU),Valorware,2020.0,2020-10-06,Valorware,"Open World, Action-RPG, Role Playing",NaN,653.00,Digital only,NaN,NaN,0,0,https://valorware.squarespace.com/9th-dawn-iii
9683,9684,7114,n Verlore Verstand,Skobbejak Games,2018.0,2018-06-12,Skobbejak Games,"Puzzle, Adventure, Platformer",NaN,2170.88,Digital only,NaN,NaN,0,0,http://skobbejakgames.com/n-verlore-verstand/
9684,9685,7110,n Verlore Verstand (EU),Skobbejak Games,2018.0,2018-06-12,Skobbejak Games,"Puzzle, Adventure, Platformer",NaN,2170.88,Digital only,NaN,NaN,0,0,http://skobbejakgames.com/n-verlore-verstand/
9685,9686,14118,Klang 2 (JP) (PS4),Ratalaika Games,2021.0,2021-11-17,Tinimations,NaN,Cross-Buy,NaN,Digital only,NaN,NaN,0,0,NaN

# MENCARI INFORMASI TENTANG 
# - JUMLAH RECORD
# - NAMA ATRIBUTE
# - JUMLAH ATRIBUTE
# - TIPE OBJEK DENGAN JUMLAH ATRIBUTE
# - TIPE ANGKA DENGAN JUMLAH ATRIBUTE YANG MEMILIKI NILAI NULL

In [17]:
df.dtypes

ID                         int64
GamePSID                   int64
GameName                  object
Publisher                 object
ReleaseYear              float64
ReleaseDate               object
Developer                 object
Genre                     object
Features                  object
Size                     float64
Medium                    object
Hardware                  object
CompletionTime(Hours)     object
is_Digital_game            int64
is_Physical_game           int64
OfficialWebsite           object
dtype: object

# MEMBUAT DICTIONARY DENGAN KEY SESUAI NAMA INFORMASINYA

In [18]:
total_record = len(df)
nama_attribute = df.columns
jumlah_objek = len(df.select_dtypes(include=['object']).columns)
jumlah_angka = len(df.select_dtypes(include=['int64', 'float64']).columns)
jumlah_NULL = len(df.columns[df.isna().sum() > 0])

dictionary_ps = {
    "Total Record": total_record,
    "Nama Attribute": nama_attribute,
    "Jumlah Objek": jumlah_objek,
    "Jumlah Angka": jumlah_angka,
    "Jumlah NULL": jumlah_NULL,
}

pd.Series(dictionary_ps)

Total Record                                                   9686
Nama Attribute    Index(['ID', 'GamePSID', 'GameName', 'Publishe...
Jumlah Objek                                                     10
Jumlah Angka                                                      6
Jumlah NULL                                                      11
dtype: object

# MENAMPILKAN RATA - RATA, STANDAR DEVIASI, NILAI MINIMUM, NILAI MAKSIMUM, Q1, Q2, Q3 DARI ATRIBUTE BERTIPE ANGKA

In [19]:
df.describe()

,ID,GamePSID,ReleaseYear,Size,is_Digital_game,is_Physical_game
count,9686.000000,9686.000000,8952.000000,7.666000e+03,9686.0,9686.0
mean,4843.500000,7450.627813,2018.515304,5.207188e+03,0.0,0.0
std,2796.251688,4434.041993,2.014025,1.880542e+04,0.0,0.0
min,1.000000,-5590.000000,2009.000000,1.100000e+01,0.0,0.0
25%,2422.250000,5108.250000,2017.000000,3.922500e+02,0.0,0.0
50%,4843.500000,7972.500000,2019.000000,1.392640e+03,0.0,0.0
75%,7264.750000,10749.750000,2020.000000,4.710400e+03,0.0,0.0
max,9686.000000,14229.000000,2022.000000,1.002496e+06,0.0,0.0

# MENAMPILKAN NILAI KORELASI ATRIBUTE BERTIPE ANGKA

In [20]:
df.select_dtypes(include=['int64', 'float64']).corr()

,ID,GamePSID,ReleaseYear,Size,is_Digital_game,is_Physical_game
ID,1.000000,0.042590,0.029937,0.004038,NaN,NaN
GamePSID,0.042590,1.000000,0.971691,-0.078626,NaN,NaN
ReleaseYear,0.029937,0.971691,1.000000,-0.083440,NaN,NaN
Size,0.004038,-0.078626,-0.083440,1.000000,NaN,NaN
is_Digital_game,NaN,NaN,NaN,NaN,NaN,NaN
is_Physical_game,NaN,NaN,NaN,NaN,NaN,NaN

# MERUBAH NILAI SALAH SATU ATRIBUTE BERTIPE ANGKA DARI BULAT MENJADI DESIMAL

In [21]:
df = df.fillna(0)
df.ID.astype('float64')

0          1.0
1          2.0
2          3.0
3          4.0
4          5.0
         ...
9681    9682.0
9682    9683.0
9683    9684.0
9684    9685.0
9685    9686.0
Name: ID, Length: 9686, dtype: float64

# MENAMPILKAN 10 RECORD PERTAMA DARI ATRIBUTE BERTIPE ANGKA

In [22]:
df.select_dtypes(include=['int64', 'float64']).head(10)

   ID  GamePSID  ReleaseYear     Size  is_Digital_game  is_Physical_game
0   1      3045       2015.0   109.00                0                 0
1   2      3051       2015.0   127.00                0                 0
2   3      6703       2018.0  2682.88                0                 0
3   4      3403       2015.0  1945.60                0                 0
4   5     13176       2021.0     0.00                0                 0
5   6     -2913          0.0     0.00                0                 0
6   7     -4119          0.0     0.00                0                 0
7   8     -4106          0.0     0.00                0                 0
8   9     12156       2021.0     0.00                0                 0
9  10     12157       2021.0     0.00                0                 0

# MENYIMPAN DATASET DENGAN ATRIBUTE BERTIPE ANGKA KE DALAM FILE CSV

In [30]:
df.select_dtypes(include=['int64', 'float64']).to_csv("Atribut_Bertipe_Angka_PS4.csv", index=False)